# Generated by Django 3.1.3 on 2020-12-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0002_auto_20201118_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
