# Generated by Django 3.1.3 on 2020-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201205_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
